from __future__ import annotations

from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import RGBColor

BLUE = RGBColor(0x00, 0x2F, 0x6C)

SRC = Path("/Users/shixiaolei/Documents/Circleup/project79_work/Project 79 - Financial Information revised markup AR Q1 20260528.docx")
OUT = Path("/Users/shixiaolei/Documents/Circleup/project79_work/Project 79 - Financial Information revised markup AR Q1 yoy 20260528.docx")


def mark(p, text):
    p.clear()
    r = p.add_run(text)
    r.font.color.rgb = BLUE
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY


def replace(doc, prefix, text):
    for p in doc.paragraphs:
        if p.text.strip().startswith(prefix):
            mark(p, text)
            return
    raise RuntimeError(prefix)


def main():
    doc = Document(SRC)

    # Three months ended March 31, 2026 vs 2025: Q1 2025 numbers are largely unavailable in the latest main statements.
    replace(doc, "Our revenue increased by [●]%", "Our revenue increased by [●]% from RMB[●] million for the three months ended March 31, 2025 to RMB81.5 million for the three months ended March 31, 2026, primarily due to the rapid growth of Agentic MaaS and continued commercialisation of our platform software and AGI enterprise solutions. In particular, management attributes the growth in the first quarter of 2026 to increased demand from large model companies and enterprise customers, higher MaaS usage following increased model and application demand, and the fact that our commercialisation activities were more developed in 2026 than in the corresponding period of 2025. [Reporting Accountants to confirm 2025 Q1 comparative amount and percentage change.]")
    replace(doc, "Agentic platform software: Our revenue from agentic platform software increased by [●]%", "Agentic platform software: Our revenue from agentic platform software increased by [●]% from RMB[●] million for the three months ended March 31, 2025 to RMB[●] million for the three months ended March 31, 2026, primarily driven by continued demand for standardised platform software for heterogeneous computing orchestration and AI operation management. The number of customers and projects should be updated once the relevant operating data is confirmed.")
    replace(doc, "AGI enterprise solutions: Our revenue from AGI enterprise solutions increased by [●]%", "AGI enterprise solutions: Our revenue from AGI enterprise solutions increased by [●]% from RMB[●] million for the three months ended March 31, 2025 to RMB[●] million for the three months ended March 31, 2026, primarily driven by enterprise customers' needs for customised AI deployment and project-based solutions, subject to project delivery and acceptance schedules. The number of customers and projects should be updated once the relevant operating data is confirmed.")
    replace(doc, "Agentic MaaS: Our revenue from Agentic MaaS increased by [●]%", "Agentic MaaS: Our revenue from Agentic MaaS increased by [●]% from RMB[●] million for the three months ended March 31, 2025 to RMB[●] million for the three months ended March 31, 2026, primarily driven by substantially higher customer usage and token/API consumption, increasing demand from large model companies and management's view that Agentic MaaS became a more significant revenue contributor in early 2026. [Company to confirm 2025 Q1 comparative data and operating metrics.]")
    replace(doc, "Our cost of sales increased by [●]%", "Our cost of sales increased by [●]% from RMB[●] million for the three months ended March 31, 2025 to RMB64.7 million for the three months ended March 31, 2026, primarily due to the increase in revenue and the higher contribution from computing-resource-intensive businesses, especially Agentic MaaS, which requires server, cloud and computing resource leasing or procurement inputs.")
    replace(doc, "As a result of the above, our gross profit increased by [●]%", "As a result of the above, our gross profit increased by [●]% from RMB[●] million for the three months ended March 31, 2025 to RMB16.8 million for the three months ended March 31, 2026. Our gross profit margin [increased/decreased] from [●]% to 20.6%, primarily due to the change in business mix, with a greater revenue contribution from MaaS and other computing-resource-intensive services, and the impact of computing resource leasing/procurement costs during a period of rapid revenue growth.")
    replace(doc, "Our other income [increased/decreased]", "Our other income [increased/decreased] by [●]% from RMB[●] million for the three months ended March 31, 2025 to RMB9.0 million for the three months ended March 31, 2026, primarily reflecting government grants, interest income and other income relating to computing resource arrangements. [Reporting Accountants to confirm 2025 Q1 comparative breakdown.]")
    replace(doc, "Our impairment losses under ECL model, net of reversal, [increased/decreased]", "Our impairment losses under ECL model, net of reversal, [increased/decreased] by [●]% from RMB[●] million for the three months ended March 31, 2025 to RMB3.2 million for the three months ended March 31, 2026, primarily due to the increase in trade and other receivables following the rapid revenue growth in the first quarter of 2026, with certain receivables not yet collected as of March 31, 2026 but remaining within the relevant credit period.")
    replace(doc, "Our selling and distribution expenses [increased/decreased]", "Our selling and distribution expenses [increased/decreased] by [●]% from RMB[●] million for the three months ended March 31, 2025 to RMB13.0 million for the three months ended March 31, 2026, primarily due to sales team expansion, market promotion, customer engagement and commercialisation activities to support business growth.")
    replace(doc, "Our administrative expenses [increased/decreased]", "Our administrative expenses [increased/decreased] by [●]% from RMB[●] million for the three months ended March 31, 2025 to RMB20.3 million for the three months ended March 31, 2026, primarily due to increases in personnel costs and general corporate and compliance expenses as our business and operating scale expanded.")
    replace(doc, "Our research and development expenses [increased/decreased]", "Our research and development expenses [increased/decreased] by [●]% from RMB[●] million for the three months ended March 31, 2025 to RMB93.4 million for the three months ended March 31, 2026, primarily due to R&D projects planned at the beginning of the year, continued investment in heterogeneous computing scheduling, model training and inference optimisation, MaaS platform capabilities and related computing resource and personnel inputs.")
    replace(doc, "Our finance costs [increased/decreased]", "Our finance costs [increased/decreased] by [●]% from RMB[●] million for the three months ended March 31, 2025 to RMB44.9 million for the three months ended March 31, 2026, primarily due to interest accrued on financial liabilities on shares with preferential rights, interest on lease liabilities and interest on bank borrowings.")
    replace(doc, "Our income tax credit [increased/decreased]", "Our income tax credit [increased/decreased] by [●]% from RMB[●] million for the three months ended March 31, 2025 to RMB3.5 million for the three months ended March 31, 2026, primarily due to movements in deferred tax arising from expected credit loss allowances, share-based payments and lease-related temporary differences.")

    # 2025 vs 2024.
    replace(doc, "Agentic platform software: Our revenue from agentic platform software increased significantly from RMB5.9 million", "Agentic platform software: Our revenue from agentic platform software increased significantly from RMB5.9 million in 2024 to RMB12.6 million in 2025, primarily driven by the fact that 2024 represented the early stage of commercialisation while 2025 was the first full year of broader commercialisation, as well as increased customer demand for standardised platform software supporting heterogeneous computing orchestration, intelligent workload scheduling and AI operation management. [Company to confirm customer and project numbers.]")
    replace(doc, "AGI enterprise solutions: Our revenue from AGI enterprise solutions increased significantly from RMB4.2 million", "AGI enterprise solutions: Our revenue from AGI enterprise solutions increased significantly from RMB4.2 million in 2024 to RMB52.0 million in 2025, primarily driven by increased enterprise demand for customised AI deployment solutions, the growth in customer number and project opportunities, and the delivery and acceptance of more solution projects in 2025 as compared with the early commercialisation stage in 2024. [Company to confirm customer and project numbers.]")
    replace(doc, "Agentic MaaS: We recorded revenue of RMB10.9 million", "Agentic MaaS: We recorded revenue of RMB10.9 million from Agentic MaaS in 2025, primarily because we began to commercialise this business line in 2025 and benefited from increasing demand from large model companies and enterprise customers for model-serving and usage-based MaaS services. Management indicated in the FDDQ that Agentic MaaS serves large model companies and is expected to be sustainable given customer demand and market growth. [Company to confirm customer number, token/API usage and other operating metrics.]")
    replace(doc, "Our cost of sales increased significantly from RMB2.2 million", "Our cost of sales increased significantly from RMB2.2 million in 2024 to RMB33.9 million in 2025, primarily in line with our revenue growth and the expansion of computing-resource-intensive businesses. The increase mainly reflected higher computing resource leasing/procurement, server and cloud service, technical service and project delivery costs, particularly as AGI enterprise solutions and Agentic MaaS became more meaningful contributors in 2025.")
    replace(doc, "As a result of the above, our gross profit increased significantly from RMB7.8 million", "As a result of the above, our gross profit increased significantly from RMB7.8 million in 2024 to RMB41.7 million in 2025. Our gross profit margin decreased from 77.7% in 2024 to 55.2% in 2025, primarily due to changes in business mix. In 2024, our revenue was generated mainly from platform software and early solution projects, while in 2025 AGI enterprise solutions and Agentic MaaS contributed a larger portion of revenue and required more computing resource and project delivery inputs. Management expects gross profit margin to be affected by resource utilisation, pricing, computing resource costs and business mix.")
    replace(doc, "Our other income remained relatively stable", "Our other income remained relatively stable at RMB37.3 million in 2024 and RMB35.7 million in 2025. Government grants increased from RMB22.0 million in 2024 to RMB23.2 million in 2025, and interest income increased from RMB7.5 million in 2024 to RMB8.3 million in 2025, partially offset by a decrease in others from RMB7.8 million in 2024 to RMB4.2 million in 2025.")
    replace(doc, "Our other gains increased from RMB0.3 million", "Our other gains increased from RMB0.3 million in 2024 to RMB1.7 million in 2025, primarily due to investment return and other gains from cash management arrangements. [Company/Reporting Accountants to confirm detailed breakdown.]")
    replace(doc, "Our selling and distribution expenses increased significantly from RMB32.9 million", "Our selling and distribution expenses increased significantly from RMB32.9 million in 2024 to RMB84.3 million in 2025, primarily due to the expansion of sales and business development personnel, increased market promotion and customer engagement activities and higher commercialisation expenses to support our broader revenue-generating activities in 2025.")
    replace(doc, "Our administrative expenses increased by 19.6%", "Our administrative expenses increased by 19.6% from RMB69.3 million in 2024 to RMB82.9 million in 2025, primarily due to higher personnel costs, increased compliance and corporate operation needs and professional service fees as our business scale expanded, partially offset by the fact that certain start-up and setup costs incurred in 2024 did not recur at the same pace in 2025.")
    replace(doc, "Our research and development expenses increased by 40.2%", "Our research and development expenses increased by 40.2% from RMB252.9 million in 2024 to RMB354.7 million in 2025, primarily due to continued investment in R&D personnel, server and computing resource costs, technical service fees, cloud service fees, depreciation and amortisation, share-based payment expenses and other R&D inputs for heterogeneous computing scheduling, model training and inference optimisation, MaaS platform capabilities, software and hardware coordination and other frontier technologies.")
    replace(doc, "We recorded share of results of associates of nil and RMB0.04 million", "We recorded share of results of associates of nil and loss of RMB0.04 million in 2024 and 2025, respectively, reflecting our share of losses from associates that were not individually material.")
    replace(doc, "As a result of the above, we recorded net loss of RMB378.2 million", "As a result of the above, we recorded net loss of RMB378.2 million and RMB579.3 million in 2024 and 2025, respectively. The increase in net loss was primarily due to higher R&D expenses, selling and distribution expenses and finance costs associated with preferred share financing, partially offset by the increase in gross profit and relatively stable other income.")

    # 2024 vs 2023.
    replace(doc, "Agentic platform software: We recorded revenue of RMB5.9 million", "Agentic platform software: We recorded revenue of RMB5.9 million from agentic platform software in 2024, mainly reflecting the commencement of commercialisation in the fourth quarter of 2024 and initial customer demand for standardised platform software supporting heterogeneous computing orchestration and AI operation management. [Company to confirm customer and project numbers.]")
    replace(doc, "AGI enterprise solutions: We recorded revenue of RMB4.2 million", "AGI enterprise solutions: We recorded revenue of RMB4.2 million from AGI enterprise solutions in 2024, mainly reflecting the commencement of commercialisation and initial delivery and acceptance of enterprise solution projects for customers with customised AI deployment needs. [Company to confirm customer and project numbers.]")
    replace(doc, "Our cost of sales increased from nil in 2023", "Our cost of sales increased from nil in 2023 to RMB2.2 million in 2024, in line with the commencement of revenue generation from platform software and AGI enterprise solutions, and primarily reflected direct costs incurred for initial project delivery and related computing resource inputs.")
    replace(doc, "As a result of the above, our gross profit increased from nil", "As a result of the above, our gross profit increased from nil in 2023 to RMB7.8 million in 2024 with gross profit margin of 77.7% in 2024, primarily because our initial revenue mix in 2024 included platform software, which generally required relatively limited incremental direct costs after product development.")
    replace(doc, "Our other income increased significantly from RMB1.2 million", "Our other income increased significantly from RMB1.2 million in 2023 to RMB37.3 million in 2024, primarily due to increases in government grants, interest income and others. Government grants increased from RMB1.2 million in 2023 to RMB22.0 million in 2024, primarily reflecting subsidies received from local governments for industry development and contributions to local economic growth; interest income increased from nil to RMB7.5 million, primarily due to interest earned on financing proceeds and bank deposits; and others increased from nil to RMB7.8 million.")
    replace(doc, "Our other gains decreased from RMB0.5 million", "Our other gains decreased from RMB0.5 million in 2023 to RMB0.3 million in 2024, primarily due to changes in investment return and other gains from cash management arrangements. [Company/Reporting Accountants to confirm detailed breakdown.]")
    replace(doc, "Our selling and distribution expenses increased significantly from RMB2.7 million", "Our selling and distribution expenses increased significantly from RMB2.7 million in 2023 to RMB32.9 million in 2024, primarily due to the expansion of our sales and business development team, increased market promotion and customer engagement activities and commercialisation preparation as we moved from the company establishment and team-building stage in 2023 to initial commercialisation in 2024.")
    replace(doc, "Our administrative expenses increased significantly from RMB14.7 million", "Our administrative expenses increased significantly from RMB14.7 million in 2023 to RMB69.3 million in 2024, primarily due to increased headcount, higher administrative personnel costs, business expansion and engagement of third-party professional advisers to support compliance, corporate operations and business growth.")
    replace(doc, "Our research and development expenses increased significantly from RMB30.6 million", "Our research and development expenses increased significantly from RMB30.6 million in 2023 to RMB252.9 million in 2024, primarily due to the expansion of our R&D team from an initial team-building stage, increased personnel costs, higher computing resource and server costs, technical service fees and cloud service fees, and continued investment in our core technologies and R&D projects.")
    replace(doc, "As a result of the above, we recorded net loss of RMB51.9 million", "As a result of the above, we recorded net loss of RMB51.9 million and RMB378.2 million in 2023 and 2024, respectively. The increase in net loss was primarily due to substantial increases in R&D expenses, selling and distribution expenses, administrative expenses and finance costs as our personnel base, R&D activities, financing activities and initial commercialisation efforts expanded, partially offset by the commencement of revenue generation and the increase in other income.")

    doc.save(OUT)
    print(OUT)


if __name__ == "__main__":
    main()
